version: "3.9"
services:
  static1:
    build: ../static
    environment:
      - APP_API=\/api
      - APP_FOO=foo1
      - APP_BAR=bar1
      - APP_NUM=1
  static2:
    build: ../static
    environment:
      - APP_API=\/api
      - APP_FOO=foo2
      - APP_BAR=bar2
      - APP_NUM=2
  node1:
    build: ../static
    environment:
      - APP_API=http:\/\/api
      - APP_FOO=foo1
      - APP_BAR=bar1
      - APP_NUM=1
  node2:
    build: ../static
    environment:
      - APP_API=http:\/\/api
      - APP_FOO=foo2
      - APP_BAR=bar2
      - APP_NUM=2
  api:
    build: ../server
  gateway:
    image: nginx:1.21.3-alpine
    links:
      - static1
      - static2
      - node1
      - node2
      - api
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
